apiVersion: apps/v1
kind: Deployment
metadata:
  name: gofiber-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gofiber
  template:
    metadata:
      labels:
        app: gofiber
    spec:
      containers:
      - name: gofiber-app
        image: struckchure/gofiber_app
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
