apiVersion: apps/v1
kind: Deployment
metadata:
  name: gofiber-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gofiber-app
  template:
    metadata:
      labels:
        app: gofiber-app
    spec:
      containers:
      - name: gofiber-app
        image: struckchure/gofiber_app
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
