apiVersion: apps/v1
kind: Deployment
metadata:
  name: expressjs-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expressjs-app
  template:
    metadata:
      labels:
        app: expressjs-app
    spec:
      containers:
      - name: expressjs-app
        image: struckchure/expressjs_app
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
